### ISSUE TITLE
关于损失函数

### ISSUE THREAD

**Issue by PuZhang-github** [lundu28/DynamicNetworkEmbedding#1]
我想请教两个问题：
1.根据新添加的边的类型不同(包括两个端点都是新增的节点或者只有一个端点是新增节点)分别计算对应节点嵌入对应的优化目标，为什么对应的μ分别是1/2，1，0？
2. 论文中损失函数L = l1+l2+l3+λl_reg，为什么代码实现中我只看到l2+l3+λl_reg，是我有什么地方理解不正确吗？

**Comment by lundu28** [comment]
1. 这样的设置保证三个loss理论上是完全等价的，直观理解就是，如果当前考虑的边两端的embedding都要调整，那么我们就让两端分别做中心节点进行采样优化，两端节点看重情况一样所以是1/2，如果是只优化一端，就只保留一项，所以是1或者0；不过 其实在实际操作中我们也可以根据效果进行一些系数的调整
2.  l1其实是被隐含包含进去了，因为l2和l3没有约束是针对只有一端要被优化的，对于两端都要优化的l2和l3分别都进行了优化，所以相当于l1也被优化了，只不过l1的系数会变成2倍，也就是l1会被更看重一些

**Comment by PuZhang-github** [comment]
非常感谢耐心解答。
